services:
  postgres:
    image: postgis/postgis:15-3.3-alpine
    restart: unless-stopped
    container_name: postgres-db
    # Support only mac m1
    platform: linux/x86_64
    shm_size: '256mb'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-1q2w3e4r}
      POSTGRES_DB: ${POSTGRES_DB:-pg-db}
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - internal

networks:
  internal:
